language: python
python:
  - "2.7"
services:
  - postgresql
install:
  - pip install --upgrade pip
  - pip install flake8
  - pip install -e ndohyep
script:
  - flake8 ndohyep
  - python ndohyep/manage.py test
after_success:
  - coveralls
