buildscript: ndohyep/sideloader/build.sh
postinstall: ndohyep/sideloader/postinstall.sh
pip:
 - gunicorn
dependencies:
 - nginx
 - postgresql-server-dev-all
 - libpq-dev
 - libffi-dev
 - postgresql
 - redis-server
 - libjpeg-dev
 - zlib1g-dev
